services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: techguy
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped
    depends_on:
      - postgres

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3.9.11-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: unless-stopped

  #  postgis:
  #    container_name: postgis
  #    image: postgis/postgis
  #    environment:
  #      POSTGRES_USER: postgres
  #      POSTGRES_PASSWORD: password
  #      PGDATA: /data/postgis
  #    volumes:
  #      - postgis:/data/postgis
  #    ports:
  #      - "5433:5433"
  #    networks:
  #      - postgis
  #    restart: unless-stopped
  #
  #  pgadmin_gis:
  #    container_name: pgadmin_gis
  #    image: dpage/pgadmin4
  #    environment:
  #      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
  #      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
  #      PGADMIN_CONFIG_SERVER_MODE: 'False'
  #    volumes:
  #      - pgadmin_gis:/var/lib/pgadmin_gis
  #    ports:
  #      - "5080:80"
  #    networks:
  #      - postgis
  #    restart: unless-stopped
  #    depends_on:
  #      - postgis

  mariadb:
    container_name: mariadb
    command: --default-authentication-plugin=mysql_native_password
    image: mariadb:10.9
    restart: always
    volumes:
      - mariadb:/data/mariadb
    ports:
      - "3306:3306"
    networks:
      - mariadb
    environment:
      MYSQL_ROOT_PASSWORD: password

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin
    restart: always
    volumes:
      - phpmyadmin:/var/lib/phpmyadmin
    ports:
      - "8080:80"
    networks:
      - mariadb
    environment:
      - PMA_ARBITRARY=1
    depends_on:
      - mariadb

networks:
  postgres:
    driver: bridge
  mariadb:
    driver: bridge
  # postgis:
  #   driver: bridge

volumes:
  postgres:
  pgadmin:
  mariadb:
  phpmyadmin:
    #  postgis:
    #  pgadmin_gis:
