services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: techguy
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped

  mariadb:
    image: mariadb:10.8
    restart: always
    volumes:
      - mariadb:/data/mariadb
    ports:
      - "3306:3306"
    networks:
      - mariadb
    environment:
      MYSQL_ROOT_PASSWORD: password

  phpmyadmin:
    image: phpmyadmin
    restart: always
    volumes:
      - phpmyadmin:/var/lib/phpmyadmin
    ports:
      - "8080:80"
    networks:
      - mariadb
    environment:
      - PMA_ARBITRARY=1

networks:
  postgres:
    driver: bridge
  mariadb:
    driver: bridge

volumes:
  postgres:
  pgadmin:
  mariadb:
  phpmyadmin: